name: galactic_time_cli_converter
description: A sample command-line application with basic argument parsing.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  gtime: galactic_time_cli_converter

